=== antonioajlb98/Lenguaje-de-marcas/Validacion xsd/Ex1t3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="relacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Members">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Member" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="yearsofmembership" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== antonioajlb98/Lenguaje-de-marcas/Validacion xsd/Ex1t3.xml
<?xml version="1.0" encoding="UTF-8"?>
<relacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Ex1t3.xsd">
    <Members>
        <Member>
            <name>Chris Smith</name>
            <yearsofmembership>4</yearsofmembership>
        </Member>
        <Member>
            <name>Judi Zimmerman</name>
            <yearsofmembership>5</yearsofmembership>
        </Member>
        <Member>
            <name>Michael Calder</name>
            <yearsofmembership>3</yearsofmembership>
        </Member>
    </Members>
</relacion>
