=== antonioajlb98/Lenguaje-de-marcas/Validacion xsd/Ex2t3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="relacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="autor" type="xs:string" />
                                        <xs:element name="year" type="xs:string" />
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="from" type="xs:string" />
                                        <xs:element name="editorial" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== antonioajlb98/Lenguaje-de-marcas/Validacion xsd/Ex2t3.xml
<?xml version="1.0" encoding="UTF-8"?>
<relacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Ex2t3.xsd">
    <books>
        <book>
            <autor>Antoniou, G. and F. van Harmelen</autor>
            <year>2004</year>
            <name>A Semantic Web Primer</name>
            <from>Cambridge</from>
            <editorial>MA: MIT Press</editorial>
        </book>
        <book>
            <autor>Daconts, M.C., L.J. Orbst, and K.T. Smith</autor>
            <year>2003</year>
            <name>The Semantic Web: A Guide to the Future of XML, Web Services, and Knowledge Management</name>
            <from>New York</from>
            <editorial>Wiley</editorial>
        </book>
    </books>
</relacion>
